services:
  # Backend API Service (backend only - frontend deployed separately)
  - type: web
    name: stock-management-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
      - key: JWT_EXPIRE
        value: 7d
    healthCheckPath: /api/auth/me
    autoDeploy: true

